### ISSUE TITLE
No issue here, just wanted ..

### ISSUE THREAD

**Issue by ETHMOONBASE** [d3noob/D3-Tips-and-Tricks#1]
No issue here, just wanted to chat with you about your auto updating line chart if you have a chance.

**Comment by d3noob** [comment]
Hi, That's some pretty old code. I suspect that it should probably be reviewed :-(.

**Comment by mivilleb** [comment]
Similar question, do you happen to have this code http://bl.ocks.org/d3noob/6bd13f974d6516f3e491  for v4 of d3? I changed the first part fine, but I have not been able to convert it so it works.

**Comment by d3noob** [comment]
Sorry, I haven't added that one to the new v4 book. I would have looked at it a year ago and I suspect that I wasn't entirely happy with what I had, so I would have moved on to easier pickings. Sorry about that. I was never that happy with the approach I took. I always felt that there should be a smarter way to do it.

**Comment by d3noob** [comment]
Closed as not really issues.
