### ISSUE TITLE
Collapsible treee diagram in v4 - license

### ISSUE THREAD

**Issue by cstadler1000** [d3noob/D3-Tips-and-Tricks#2]
Hello there !

First I would like to thank you for sharing this amazing piece of code.

I'd like to know if you could possibly add a license to the tree diagram (https://bl.ocks.org/d3noob/43a860bc0024792f8803bba8ca0d5ecd), since there appears to be none.

Keep up the great work,

Best regards,

Chris

**Comment by d3noob** [comment]
Hi Chris,

Apologies for not having a licence associated with it. Fixed now. 
Regards

Malcolm

**Comment by cstadler1000** [comment]
Thank you for the quick response !
