### ISSUE TITLE
What about a TypeScript version?

### ISSUE THREAD

**Issue by Timokasse** [d3noob/D3-Tips-and-Tricks#3]
Hello,

As you must have guessed already from the title, this is not an issue, but I don't see any other way to chat with you. Maybe you could suggest one?
At the moment I am reading your v7 document and I really appreciate the work there. It's simple, well explained and yet quite detailed already. My goal is to be able to integrate a zoomable D3 treemap in an Angular application. I see examples on the web but they are either written in JavaScript or they use a much older version of D3. So, as a first learning step, I am trying to convert all your examples into their working Angular/TypeScript equivalent. I find TypeScript very interesting to better understand the D3 logic because you have to use the right types and you have to make sure you handle corner cases like when a variable is undefined. But of course I have some questions and thoughts that I would like to share with you. Here are a few:

- Is it really a good idea to use TypeScript with D3? I see pros and cons. I would like other opinions.
- Am I converting it properly? Sometimes I feel that my code is a bit tedious and that there should be another way. Of course I will share my code if you are interested.
- Would you be interested to write a TypeScript version of your document? If not, would you be interested that I write it?
- You do not have treemaps in your document. I know it can be found elsewhere but being biases by my own initial goal, I would recommend you to add one. And even better, you could have a zoomable treemap.

Hoping to be able to chat with you soon,
Timok

**Comment by d3noob** [comment]
Hi Timok. Thanks for reaching out. 

Actually I have my email address at the start of the book (Page 7 for the v7 version :-)).
I'll see if I can answer your questions here, but if you need to get in touch in the future, feel free to use the email address :-).

_Is it really a good idea to use TypeScript with D3? I see pros and cons. I would like other opinions.
Am I converting it properly? Sometimes I feel that my code is a bit tedious and that there should be another way. Of course I will share my code if you are interested.__

I'm really sorry, but I don't have any experience with TypeScript or Angular. So I wouldn't be in a position to be able to provide you with any advice. 

_Would you be interested to write a TypeScript version of your document? If not, would you be interested that I write it?_

I'm afraid that I wouldn't be in a position to write a TypeScript version of the document. I have too many other things on my plate I'm afraid. I would be flattered if you wrote a TypeScript version of the book. I'm sorry that I wouldn't be able to assist with the writing, but if you thouht it would be useful I could proof-read perhaps?

_You do not have treemaps in your document. I know it can be found elsewhere but being biases by my own initial goal, I would recommend you to add one. And even better, you could have a zoomable treemap._

Thanks for the suggestion, but treemaps have never really grabbed me. I don't know why, but I was never inspired by them and so I have never really worked with them. Sadly that also means that I am unlikely to add them in the future (although I should never say never...).

Many thanks for your questions and I'm sorry that I didn't have better answers for you.

All the best.

Regards 

Malcolm

**Comment by Timokasse** [comment]
Thanks for your quick answer, Malcom.
Conversation to be continued by mail.
